name: MMEmoji
main: com.minemee.MMEmoji.MMEmoji
version: 1.0
description: >
             Line art for Minecraft chat.
commands:
  tableflip:
    description: Do a table flip!
  table:
    description: Do a table flip!
  dtable:
    description: Do a double table flip!
  finger:
    description: The finger!
  shrug:
    description: Shrugs.
  wtf:
    description: Wtf face.
  why:
    description: y u do dis ?
  cool:
    description: Looks like...
  cry:
    description: Crying face.
  sad:
    description: Sad face.
  dead:
    description: Dead face.
  dance:
    description: Party hard!
  gimme:
    description: Gimme, gimme!
  bighit:
    description: HIT
  visualizer:
    description: A visualizer!
  vis:
    description: A visualizer!
  spam:
    description: Spam the player! <Warning> Do not over use!
  bunny:
    description: Makes a bunny in chat!
  fixtable:
    description: Put the table back.
  throw:
    description: Get out!
  erika:
    description: Wut...
  donger:
    description: DONGER!
  wannago:
    description: You wanna go?
  snip:
    description: Snip Snip!
  lilgimme:
    description: A little gimme!
  kirk:
    description: :D